#Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.parallel=true

#Kotlin
kotlin.daemon.jvmargs=-Xmx4G
kotlin.native.binary.gc=cms

#Android
android.useAndroidX=true

#Compose
org.jetbrains.compose.experimental.macos.enabled=true
